### ISSUE TITLE
AsyncStorage com limite de 6MB

### ISSUE THREAD

**Issue by lucasgandac** [fga-eps-mds/2022.1-EuPescador-UserInterface#3]
### Descrição:
Na tela de registros ocorre um erro de limite de espaço de disco quando existe mais de 1 registro

### Tarefas
Seção para tarefas (tasks) para issues mais complexas ou sub-tarefas. 
- [ ] Aumentar capacidade do asyncStorage no gradle.

**Comment by Wictorgirardi** [comment]
https://github.com/fga-eps-mds/2022.1-EuPescador-UserInterface/pull/12
