### ISSUE TITLE
Loader no carregamento do mapa

### ISSUE THREAD

**Issue by lucasgandac** [fga-eps-mds/2022.1-EuPescador-UserInterface#5]
### Descrição:
Adicionar um loader no carregamento dos PINS no MAPA.

### Tarefas
Seção para tarefas (tasks) para issues mais complexas ou sub-tarefas. 
- [ ] Adicionar um loader/spinner na tela enquanto a API não carrega.

**Comment by flyerjohn** [comment]
Existem duas opções viáveis de apresentar o indicativo de carregamento de mapa para o usuário.
Qual seria a melhor opção considerando a visão de produto do nosso projeto?

1. Essa opção guia-se pelo padrão já utilizado no projeto:
![IMG_698EC7FC9EDD-1](https://user-images.githubusercontent.com/42387714/184170790-0a324d5d-161d-4847-bbcd-4c68e799073a.jpeg)

2. Essa opção utiliza os padrões de design do *Activity Indicator* utilizados no projeto, e adiciona um sentido de contexto para o usuário sobre qual informação ele estaria esperando a ser carregada:
![IMG_B6DB73429B27-1](https://user-images.githubusercontent.com/42387714/184171404-a38af439-2e8a-4864-9b09-b0c312960a9c.jpeg)
