### ISSUE TITLE
Buffer na localização

### ISSUE THREAD

**Issue by lucasgandac** [fga-eps-mds/2022.1-EuPescador-UserInterface#9]
### Descrição:
As coordenadas do peixe não podem ser exatas

### Tarefas
Seção para tarefas (tasks) para issues mais complexas ou sub-tarefas. 
- [ ] Colocar marcador com localização randomizada.

### Comentários ou Observações
Alguma informação necessária para melhor compreensão.

**Comment by lucasgandac** [comment]
Após conversar com o Oscar, houve a necessidade de mudar a forma como essa tarefa deve ser feita, passando de um raio de área para um ponto mas com uma localização que varia.
![image](https://user-images.githubusercontent.com/31927782/184234187-fd839396-1295-495d-b90b-6066b15753ce.png)

**Comment by Andreabenf** [comment]
Issue fechada e PR aprovado!
